### PR TITLE
Only save the files when compating tardirs.

### PR DESCRIPTION
**Pull request by 0x9900**
I'm still having intermittents problems when reboot my boxes. The sockets files are not always deleted, or sometimes they are recreated by the daemons running before the tar is completed.

In this patch only the files are saved.

### CODE REVIEW

**Comment by bconway** [comment]
That won't pick up /var/empty, which is a fairly critical part of OpenSSH and other privilege-separated programs.

**Comment by 0x9900** [comment]
I thought of that a couple of days ago. I'm going to post an another patch soon where I use mtree at boot time to create the directory tree.

**Comment by 0x9900** [comment]
This last patch only archive the files and the symlinks. When the system reboots it uses `mtree` to create the `/var` directory tree using the configuration file `/etc/mtree/flashrd.conf`

**Comment by yellowman** [comment]
can you rebase this so i can merge?

**Comment by 0x9900** [comment]
Hi Chris, I Will do that this weekend. Since you changed of things since that change was proposed I need some time to do the integration and tests.

**Comment by yellowman** [comment]
thank you :)

**Comment by 0x9900** [comment]
I've done the rebase. You can merge this branch at your convenience.

**Pull request merged**
